### PR TITLE
Fix error raised when loading a collection proxy

### LINKED ISSUE #8: Error raised when loading a collection proxy
Issue can be reproduced with the following spec:
```ruby
    it "can lazy preload associations on association collection" do
      user = User.first
      expect(user.posts).to be_a(ActiveRecord::Associations::CollectionProxy)
      expect { user.posts.load }.not_to raise_exception
    end
```

### PR DESCRIPTION
**Pull request by PikachuEXE**
Fixes #8

### CODE REVIEW

File: lib/ar_lazy_preload/active_record/collection_proxy.rb [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+  module CollectionProxy
+    def self.included(base)
+      base.prepend(Relation)
+      base.prepend(InstanceMethods)
+    end
+
+    module InstanceMethods
+      private
+
+      def _ar_lazy_preload_records
```
Comment (DmitryTsepelev) [inline lib/ar_lazy_preload/active_record/collection_proxy.rb]: I guess it will be enough to define a private method `ar_lazy_preload_records` inside the `CollectionModule` module

File: lib/ar_lazy_preload/active_record/relation.rb [hunk 2]
```diff
@@ -47,6 +52,10 @@ def lazy_preload_values
 
     private
 
+    def _ar_lazy_preload_records
+      @records || []
```
Comment (DmitryTsepelev) [inline lib/ar_lazy_preload/active_record/relation.rb]: I guess we don't need a fallback here cause when `@records` are not available we should handle this case anyway

File: spec/ar_lazy_preload/active_record/relation_spec.rb [hunk 3]
```diff
@@ -19,6 +19,12 @@
     it "raises exception on empty arguments" do
       expect { User.lazy_preload }.to raise_exception(ArgumentError)
     end
+
+    it "can lazy preload associations on association collection" do
```
Comment (DmitryTsepelev) [inline spec/ar_lazy_preload/active_record/relation_spec.rb]: I think we could move this test to the separate file `spec/ar_lazy_preload/active_record/collection_proxy_spec.rb`.

Please make sure user` is created in the `let` statement - in the current implementation the test will behave differently when it's run as a part of the suite and separately (because in the second case there are no users in the DB).

Also, it would be great to check if preloading is still working here (context is initialized properly): I think the easiest way is to check if context was set up properly

**Comment by PikachuEXE** [comment]
All issue addressed!
